import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Header from "@/components/Header";

// 1. Define metadata ONCE
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2. Define RootLayout ONCE, using the font variables directly
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
